name: py-dac actions
run-name: ${{ github.actor }} is testing out dac 🚀
on: [push]
jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🔖
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Setup python 🐍
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Setup cache 💾
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit
    - name: Before script 🙆‍♂️
      run: |
        pip install -U pip wheel setuptools pre-commit
        pre-commit install
    - name: Script 🏃‍♂️
      run: |
        pre-commit run
